<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

	<?php echo $this->HeadTitle() ."\n"; ?>
	<base href="<?php echo Zend_Registry::get('config')->paths->admin->base; ?>/" />

	<link rel="stylesheet" type="text/css" href="styles/bootstrap/bootstrap.min.css"/>
	<link rel="stylesheet" type="text/css" href="styles/libs/font-awesome.css"/>
	<link rel="stylesheet" type="text/css" href="styles/libs/nanoscroller.css"/>
	<link rel="stylesheet" type="text/css" href="styles/compiled/theme_styles.css"/>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:400,600,700,300|Titillium+Web:200,300,400">

	<script src="scripts/jquery.js"></script>
	<script src="scripts/bootstrap.js"></script>
	<script src="scripts/jquery.nanoscroller.min.js"></script>
	<script src="scripts/scripts.js"></script>
    <script src="scripts/validation/jquery.validate.min.js"></script>
    <script src="scripts/validation/localization/messages_pt_BR.js"></script>

	<!--[if lt IE 9]>
		<script src="scripts/html5shiv.js"></script>
		<script src="scripts/respond.min.js"></script>
	<![endif]-->

    <script type="text/javascript">
        $(document).ready(function(){
            $('#frmEsqueci').validate({
                rules: {
                    email: {required: true, email: true}
                },
                errorElement: 'span',
                errorClass: 'help-block',
                errorPlacement:function(error, element){
                    if(element.parent('.input-group').length) {
                        error.insertAfter(element.parent());
                    } else {
                        error.insertAfter(element);
                    }
                },
                highlight: function(element) {
                    $(element).closest('.input-group').addClass('has-error');
                },
                unhighlight: function(element) {
                    $(element).closest('.input-group').removeClass('has-error');
                },
                submitHandler: function(form) {
                    $('.alert-success').removeClass('hidden').hide();
                    $('.alert-danger').removeClass('hidden').hide();
                    $.ajax({
                        url: '<?php echo $this->BaseUrl(); ?>/login/esqueci-senha',
                        cache: false,
                        type: 'POST',
                        dataType: 'json',
                        data: $(form).serialize(),
                        success: function(retorno) {
                            if (retorno.success) {
                            	$('#serverMessageSuccess').html(retorno.message);
                                $('.alert-success').removeClass('hidden').show();
                            } else {
                                $('#serverMessageError').html(retorno.message);
                                $('.alert-danger').removeClass('hidden').show();
                            }
                        }
                    });

                    return false;
                }
            });
        });
    </script>
</head>
<body id="login-page-full" class="<?php echo Zend_Registry::get('configInfo')->tema; ?>">
	<div id="login-full-wrapper" class="reset-password-wrapper">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<div id="login-box">
						<div id="login-box-holder">
							<div class="row">
								<div class="col-xs-12">
									<header id="login-header">
										<div id="login-logo">
											<img src="img/logo.png" alt=""/>
										</div>
									</header>
									<div id="login-box-inner" class="with-heading">
										<h4>Esqueceu sua senha?</h4>
										<p>Informe seu e-mail para receber a senha.</p>
                                        <form id="frmEsqueci" role="form">
                                            <div class="alert alert-danger hidden">
                                                <i class="fa fa-times-circle fa-fw fa-lg"></i>
                                                <strong>Erro!</strong> <span id="serverMessageError"></span>.
                                            </div>
                                            <div class="alert alert-success hidden">
                                                <i class="fa fa-check-circle fa-fw fa-lg"></i>
                                                <strong>Sucesso!</strong> <span id="serverMessageSuccess"></span>.
                                            </div>
											<div class="input-group reset-pass-input">
												<span class="input-group-addon"><i class="fa fa-user"></i></span>
                                                <input type="text" id="email" name="email" maxlength="100" class="form-control" placeholder="E-mail">
											</div>
											<div class="row">
												<div class="col-xs-12">
													<button type="submit" class="btn btn-success col-xs-12">Reenviar Senha</button>
												</div>
												<div class="col-xs-12">
													<br/>
													<a href="<?php echo $this->BaseUrl(); ?>/login" id="login-forget-link" class="forgot-link col-xs-12">Voltar para o login</a>
												</div>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>